# action.yaml
name: "Blog Custom Github Action"
description: "call agify API and get age"
inputs:
  name:
    description: "get age based on name"
    required: true
    default: 1
outputs:
  age:
    description: "age of the named person"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name}}
