on:
  workflow_dispatch: # triggers manually

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Get person name
        uses: ./ # Uses an action in the root directory
        id: name
        with:
          name: bella
